version: '2'  
services:  
  nginx:
    image: nginx:latest
    container_name: nginxlapandilla
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - ./src/static:/static             
    depends_on:
      - web
  db:
    image: postgres:latest
    container_name: psqllapandilla
    ports:
     - "5434:5432"    
  web:
    build: .
    container_name: djangolapandilla
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn --timeout 120 lapandilla.wsgi -b 0.0.0.0:8000 "
    depends_on:
      - db
    volumes:
      - ./src:/src
      - ./src/static:/static       
    expose:
      - "8000"
    links:
      - db
      - redis         
  redis:
    image: "redis:alpine"
    container_name: redislapandilla
  #worker:
    #build:
      #context: .
      #dockerfile: Dockerfile
    #command: bash -c "celery worker -A lapandilla.celeryconf -Q default -n default@%h"
    #container_name: celerylapandilla    
    #volumes:
      #- ./src:/src
    #links:
      #- db
      #- redis
    #depends_on:
      #- redis    
